# 1. Image reference overrides mapping to Docker's Hardened Registry
image:
  repository: dhi.io/keycloak
  tag: "26.7.0"  # https://www.keycloak.org/docs/latest/release_notes/index.html

imagePullSecrets:
  - name: dhi-pull-secret

# 2. Expose the dashboard using your Cilium LoadBalancer IP Pool
service:
  type: LoadBalancer
  httpPort: 80

# 3. Microservice Environment Properties Variables
extraEnv: |
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: "password"
  - name: KC_HOSTNAME_STRICT
    value: "false"

# 4. Storage configuration dynamically mapped to your Longhorn engine
database:
  vendor: dev-file # Uses file-based storage mapped directly to your Longhorn disk

persistence:
  enabled: true
  storageClass: "longhorn"
  size: 5Gi
